- hosts: localhost
  tasks:
  - name: install Git
    yum: name=git state=latest
    become: yes
    become_method: sudo      
  - name: clone myrepo
    git: repo=https://github.com/shimib/myrepo.git dest=~/repo update=no
  - name: clone petclinic 
    git: repo=https://github.com/shimib/spring-petclinic.git dest=~/petclinic
  - name: create Maven directory
    file: path=~/maven state=directory mode=0755
  - name: install Maven
    unarchive: src="http://apache.spd.co.il/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz" dest=~/maven copy=no creates=~/maven/apache-maven-3.3.9/README.txt
  - name: set env m2_home
    lineinfile: dest=/home/ec2-user/.bash_profile regexp="^M2_HOME.*" line="M2_HOME=/home/ec2-user/maven/apache-maven-3.3.9" insertbefore="^PATH="
  - name: export M2_HOME
    lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="export M2_HOME"
  - name: set M2
    lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2_HOME=" line="M2=$M2_HOME/bin"
  - name: export M2
    lineinfile: dest=/home/ec2-user/.bash_profile insertafter="^M2=" line="export M2"
  - name: Add M2 to PATH
    lineinfile: dest=/home/ec2-user/.bash_profile regexp="^PATH=.*:$M2" insertafter="^PATH=" line="PATH=$PATH:$M2"
  - name: Install Docker
    yum: name=docker state=latest
    become: yes
    become_method: sudo
  - name: Add docker group to ec2-user
    user: append=yes groups=docker name=ec2-user
    become: yes
    become_method: sudo
  - name: Start Docker Service
    service: name=docker state=started
    become: yes
    become_method: sudo
  - name: Ensure Jenkins Yum repo present
    become: yes
    become_method: sudo
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo
           dest=/etc/yum.repos.d/jenkins.repo mode=0644
  - name: Ensure Jenkins GPG key installed
    command: rpm --import http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
    become: yes
    become_method: sudo
  - name: Ensure Jenkins installed
    yum: name=jenkins state=present
    become: yes
    become_method: sudo
  - name: Ensure Jenkins is running
    service: name=jenkins state=running enabled=true
    become: yes
    become_method: sudo
